name: Lint PHP code style issues

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  lint-php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check PHP code style issues
        uses: aglipanci/laravel-pint-action@61f2bc4f4d5da076029d370fa2f268fd6b298041 # 2.3.1
        with:
          testMode: true
          verboseMode: true
